version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/
      - /node_modules
    ports:
      - "3000:3000"